name: vérification du client 

on:
  push:
    branches:
      - 14-create-create-CI-CD

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.6

    - name: Installer les dépendances Go
      run: go get -v -t -d ./...

    - name: Display Go version
      run: go version

    - name: Compilation du code
      run: go build ./...


  coverage:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.6

    - name: Installer golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

    - name: Exécuter golangci-lint
      run: golangci-lint run ./...

    - name: Exécuter les tests avec la couverture de code
      run: |
        go test -coverprofile=coverage.out ./...

    - name: Afficher le rapport de couverture de code
      run: go tool cover -func=coverage.out


  check-before-merge:
    runs-on: ubuntu-latest
    needs: coverage

    steps:
    - name: Vérifier le statut du workflow
      run: echo "Le workflow a réussi. Autoriser le merge."