name: client workflow

on:
  push:
    branches:
      - 14-create-create-CI-CD # main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.6
    
    - name: Installing golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

    - name: run golangci-lint
      run: golangci-lint run ./...
    

  build:
    runs-on: ${{ matrix.os }}
    needs: lint

    strategy:
      matrix:
        os: [ubuntu-latest] # [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.6

    - name: Installing Go dependency
      run: go get -v -t -d ./...

    - name: Display Go version
      run: go version

    - name: Code compilation
      run: go build ./...


  coverage:
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest] # [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.6

    - name: generate test coverage
      run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        profile: cover.out
        local-prefix: github.com/org/project
        threshold-file: 70
        threshold-package: 80
        threshold-total: 90

    - name: Badge generation
      run: echo -n "![Code Coverage](https://img.shields.io/badge/coverage-$(< cover_percentage.txt)%-brightgreen)" > coverage-badge.svg

    - name: Extract percentage coverage
      run: go tool cover -func=cover.out | awk 'END { print int($3) }' > cover_percentage.txt

    - name: Commit badge to repository
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add coverage-badge.svg cover_percentage.txt
        git commit -m "Add badge" || true
        git push

