name: client workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.6

    - name: Installing Go dependency
      run: go get -v -t -d ./...

    - name: Display Go version
      run: go version

    - name: Code compilation
      run: go build ./...


  coverage:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.6

    - name: Installing golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest

    - name: run golangci-lint
      run: golangci-lint run ./...

    - name: Run tests with code coverage
      run: |
        go test -coverprofile=coverage.out ./...

    - name: View code coverage report
      run: go tool cover -func=coverage.out